### ISSUE TITLE
Deprecation Warning: Using / for division

### ISSUE THREAD

**Issue by openprivacy** [CivicActions/ca-jekyll-vanilla#22]
When running `jekyll serve` locally (ubuntu 22.04, ruby 3.0.2p107) it runs but I get many of these warnings:

> Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
> Recommendation: math.div(100% * 4, 12) or calc(100% * 4 / 12)
> More info and automated migrator: https://sass-lang.com/d/slash-div

**Comment by dmundra** [comment]
Thanks @openprivacy. It is not blocking warning and also I believe it is upstream warning that affects https://github.com/18F/uswds-jekyll
